const general:Record<string,any>={
 "fashion-video":{title:"AI 服饰带货模板体系",company:"快手 · 快影",image:"/media/editorial/fashion-video-system-v2.png",caption:"从一张服饰商品图出发，经过主体保持、动作迁移与换装组合，生成对镜、舞蹈、变装和户外等多种带货视频模板。",theme:"用模板、模型选型与穿搭规则稳定生成效果",summary:"服饰视频需要同时解决动作、换装、主体一致性和搭配审美。我归纳五类热门模板，并按效果与成本选择不同模型与生成路径。",steps:[["模板归纳","对镜、跳舞、卡点变装、图文、户外五类高频样式"],["模型选型","豆包生图、可灵动作模仿、爱诗主体替换按效果与成本组合"],["质量约束","分阶段生成并加入穿搭规则，减少不协调与主体漂移"]],metrics:[["1 万+","上线两周 DAU"],["4 万","次月 DAU"],["59% → 75%","生图到生视频转化"],["78%","穿搭好评率"]]},
 "monetization-strategy":{title:"商业化定价与免费策略",company:"快手 · 快影",theme:"让定价同时满足成本、用户感知与长期增长",summary:"生成类产品的每次尝试都有真实成本。我的判断不是简单涨价或免费，而是把模板拆为原子能力核算成本，并用四维框架设计价格与免费额度。",steps:[["成本底线","拆解五类模板所调用的原子能力与单次生成成本"],["四维定价","结合成本底线、竞品水位、用户感知和运营目标"],["免费实验","将免费定义为 CPL，权衡短期亏损与长期 LTV"]],metrics:[["4.5 万","合并月收入"],["636","LTV"],["13:1","ROI"],["35%","免费组 7 日复购"]]},
 "ai-keyboard":{title:"键盘端场景化主动推荐",company:"科大讯飞",theme:"让 AI 在用户需要时出现，同时保持克制",summary:"输入法是高频、即时且低摩擦的场景，要求推荐既准确又不能打扰。我设计两阶段语义标准化、向量匹配和频率控制，并通过多档阈值 AB 找到平衡。",steps:[["离线标准化","用 DeepSeek 提炼助手描述的四个核心要素"],["在线匹配","轻量模型生成同格式语义串并完成向量检索"],["打扰控制","每小时不超过一次、每天不超过三次，并测试多档阈值"]],metrics:[["35%","推荐点击率"],["+56%","上屏率"],["17% → 32%","AI 助手 UV 渗透率"],["< 2%","投诉 / 关闭率"]]},
 "assistant-builder":{title:"AI 助手创建流程优化",company:"科大讯飞",theme:"把等待中的流失转化为可召回的创建过程",summary:"头像、名称和描述生成带来明显等待，原同步流程让大量用户中途退出。我以实时渲染、异步执行、主动召回和示例引导重构创建链路。",steps:[["即时反馈","创建过程中实时渲染头像、名称与描述"],["异步执行","用户离开后继续生成，通过 APP 推送与场景弹窗召回"],["降低门槛","用滑动式示例帮助用户理解一句话应该如何描述需求"]],metrics:[["58% → 27%","创建流失率"],["28% → 53%","创建成功率"],["12.3% → 31.7%","次日留存"],["5 万 → 12 万","平台 DAU"]]},
 "dify-workflow":{title:"折叠式创建与渐进披露",company:"科大讯飞",theme:"一个入口，同时服务普通用户与进阶用户",summary:"默认只保留一个需求输入框，由系统完成一句话生成；背景、指令和知识库等高阶配置折叠隐藏，在零门槛与可控性之间取得平衡。",steps:[["默认路径","普通用户只需一句话即可生成助手"],["高阶配置","背景、指令、知识库按需展开"],["分层验证","分别观察首次创建成功率和高级配置使用情况"]],metrics:[["56%","普通用户首创成功率"],["10%","高阶配置使用率"]]},
 "hangup-optimization":{title:"ASR / TTS / 大模型全链路优化",company:"百融云创",theme:"一次挂断背后，是识别、生成、语音和延时共同作用",summary:"针对券商智能外呼高挂断问题，我从西南方言识别、TTS 口语感与触发时机、三层 RAG 召回及低置信度兜底四个环节联合优化。",steps:[["听清","建立方言对照表、专项标注与 20% 抽检"],["说自然","加入 TTS 口水词，并前移逗号、顿号、问号触发时机"],["答准确","关键词、向量、重排三层召回，叠加合规 Prompt 与澄清兜底"]],metrics:[["56% → 43%","挂断率"],["45% → 20%","ASR 错误率"],["73% → 89%","意图识别率"],["1.5s → 0.8s","首包延时"]]},
 "rag-loop":{title:"双维度评测闭环",company:"百融云创",theme:"让客户验收从主观感受转向业务证据",summary:"我把技术质量与业务结果放进同一套评测框架，并建立从小流量灰度、AB 对比、人工抽检到全量上线及日度 Badcase 巡检的闭环。",steps:[["技术维度","持续跟踪 ASR、NLP、LLM 与 TTS 指标"],["业务维度","对齐挂断率、高意向率和短信点击率"],["上线机制","小流量灰度、AB、人工抽检、全量与日度巡检"]],metrics:[["2 类","技术 + 业务评测维度"],["5 步","完整上线验证流程"],["日度","Badcase 巡检频率"]]}
};
const vibes:Record<string,any>={
 "shiguang-intent":{title:"时光意图",en:"SHIGUANG INTENT",tag:"个人时间与意图管理实验",url:"https://shiguang-intent.jazzy-hen-8182.chatgpt.site",image:"/media/editorial/research-garden.png",question:"人们记录了很多待办，却很少记录一件事为什么值得做。如何让稍纵即逝的意图被保存、重新理解，并在合适的时间再次出现？",audience:"希望整理长期愿望、灵感和生活计划，但不喜欢传统任务工具压力感的人。",principles:[["意图先于任务","先记录意义和情绪，再决定是否行动。"],["时间不是列表","用时间线与阶段关系呈现想法如何生长。"],["轻量但有回声","降低记录成本，让过去的自己在未来重新出现。"]],flow:["生活观察与问题定义","信息结构与内容语气","视觉系统和交互原型","AI 协作开发与上线","真实使用后的持续调整"],reflection:"这个项目让我重新理解“个人工具”：它不必用效率要求用户，也可以是一种温和的自我理解媒介。"},
 "reborn-market":{title:"Reborn Market",en:"REBORN MARKET",tag:"循环消费与物品故事实验",url:"https://reborn-market.jazzy-hen-8182.chatgpt.site",image:"/media/editorial/project-path.png",question:"二手交易常被简化成价格与成色，但一件物品也承载使用痕迹和故事。如何让再流通不仅是交易，也成为价值被重新发现的过程？",audience:"在意审美、物品故事与可持续生活，希望获得更有温度的闲置体验的人。",principles:[["重新定义价值","从折旧商品转向具有下一段生命的物品。"],["故事辅助决策","用来源、使用方式和状态信息建立信任。"],["品牌即体验","视觉、内容和交互共同表达循环理念。"]],flow:["循环消费趋势观察","用户与品牌命题定义","市场结构与交易路径","视觉语言和内容设计","Vibe Coding 构建可访问产品"],reflection:"这次实验验证了产品经理可以同时承担策略、品牌、交互与开发组织者，让一个模糊概念快速接受真实体验的检验。"}
};
export default async function ProjectCase({params}:{params:Promise<{slug:string}>}){const{slug}=await params;if(vibes[slug])return <Vibe item={vibes[slug]}/>;const item=general[slug]??general["fashion-video"];return <main className="case-page"><header className="page-nav"><a href="/projects">← 项目索引</a><b>THOUGHT GARDEN</b><a href="/experience">实习经历</a></header><section className="case-hero"><span>{item.company} · AI PRODUCT CASE</span><h1>{item.title}</h1><p>{item.theme}</p></section>{item.image?<figure className="case-editorial"><img src={item.image} alt={`${item.title} 项目视觉`}/><figcaption><span>生成路径</span><p>{item.caption}</p></figcaption></figure>:slug==="monetization-strategy"?<section className="pricing-visual"><header><span>PRICING ARCHITECTURE</span><h2>从生成成本到长期价值</h2></header><div className="pricing-flow"><article><i>01</i><b>原子能力</b><small>生图 · 生视频 · 动作 · 换装</small></article><em>→</em><article><i>02</i><b>成本底线</b><small>单次调用成本 × 模板组合</small></article><em>→</em><article><i>03</i><b>用户定价</b><small>竞品 · 感知 · 运营目标</small></article><em>→</em><article><i>04</i><b>免费实验</b><small>CPL → 复购 → LTV</small></article></div><div className="pricing-orbit"><div><b>成本</b><span>可持续底线</span></div><div><b>竞品</b><span>市场水位</span></div><div><b>感知</b><span>付费意愿</span></div><div><b>运营</b><span>增长目标</span></div><strong>价格<br/>决策</strong></div></section>:null}<section className="case-question"><small>THE QUESTION / 核心问题</small><h2>{item.summary}</h2></section><section className="case-path"><header><small>SOLUTION MAP</small><h2>方案不是三个要点，<br/>而是一条连续的决策路径。</h2></header><div>{item.steps.map((x:string[],i:number)=><article key={x[0]}><span>0{i+1}</span><div className="case-path__node"><i/></div><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section><section className="case-dashboard"><header><small>IMPACT DASHBOARD</small><h2>关键指标</h2><p>用同一组结果同时检查体验改善、业务增长与方案可持续性。</p></header><div className="case-dashboard__grid">{item.metrics.map((x:string[],i:number)=><article key={x[1]}><span>0{i+1}</span><b>{x[0]}</b><p>{x[1]}</p><div className="case-spark"><i style={{height:`${42+i*13}%`}}/><i style={{height:`${58+i*9}%`}}/><i style={{height:`${76+i*6}%`}}/><i style={{height:`${92-i*3}%`}}/></div></article>)}</div></section><section className="case-result"><small>MY TAKEAWAY</small><h2>把技术不确定性拆成<br/>可以被验证的产品问题。</h2><a href="/projects">浏览全部项目 →</a><a href="/experience">返回实习经历 →</a></section></main>}
function Vibe({item}:{item:any}){return <main className="vibe-case"><header className="page-nav"><a href="/research">← 研究与实验</a><b>THOUGHT GARDEN</b><a href="/projects">全部项目</a></header><section className="vibe-cover"><img src={item.image} alt={`${item.title} 项目封面`}/><div><span>VIBE CODING · INDEPENDENT PROJECT</span><h1>{item.title}</h1><b>{item.en}</b><p>{item.tag}</p><a href={item.url} target="_blank" rel="noreferrer">访问真实项目 ↗</a></div></section><section className="vibe-question"><span>WHY THIS PROJECT</span><h2>{item.question}</h2><div><small>TARGET USER</small><p>{item.audience}</p></div></section><section className="vibe-principles"><header><span>PRODUCT PRINCIPLES</span><h2>三个设计原则</h2></header><div>{item.principles.map((x:string[],i:number)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section><section className="vibe-timeline"><header><span>FROM IDEA TO LIVE SITE</span><h2>从想法到上线</h2></header><div>{item.flow.map((x:string,i:number)=><article key={x}><i>{String(i+1).padStart(2,"0")}</i><b>{x}</b><span style={{width:`${20*(i+1)}%`}}/></article>)}</div></section><section className="vibe-stack"><div><span>MY ROLE</span><h2>产品定义<br/>体验设计<br/>内容策略<br/>AI 协作开发</h2></div><div><span>WORKING METHOD</span><p>把需求拆成可执行的小步，用 AI 辅助研究、文案、界面与代码；每一步都回到真实页面检查，再继续下一轮。</p><dl><div><dt>01</dt><dd>Define</dd></div><div><dt>02</dt><dd>Prototype</dd></div><div><dt>03</dt><dd>Build</dd></div><div><dt>04</dt><dd>Refine</dd></div></dl></div></section><section className="vibe-reflection"><span>REFLECTION</span><h2>{item.reflection}</h2><a href={item.url} target="_blank" rel="noreferrer">打开 {item.title} ↗</a></section></main>}
